#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const DATA_PATH = path.join(__dirname, '../public/rfp_data.json');
const data = JSON.parse(fs.readFileSync(DATA_PATH, 'utf8'));

const patches = {

  13: `BRIM connects to BSB's landing page through REST APIs. When a prospect FI completes the interest form on BSB's branded landing page, an API call creates a prospect record in BRIM's partner management module with all submitted fields — FI name, charter type, asset size, contact info, and product interest. BSB's team sees the new prospect in the admin portal with status tracking. No CSV uploads, no manual data entry. Once BSB approves the prospect for onboarding, the Golden Copy template activates with pre-configured options across networks, BINs, customer support flows, origination journeys, UI/UX, reporting, fraud and risk rules, reconciliation, correspondence, and credit decisioning. The partner FI selects their options and BRIM configures. Full-lifecycle agent bank onboarding runs two weeks from signed agreement to live cards using the Golden Copy template. This is how AFFINITY CREDIT UNION's agent banking partners onboard today. The integration requires standard REST API connectivity. BRIM provides the API spec and BSB's web team connects the landing page form — typical integration effort is two to three days.`,

  15: `BSB's outreach to prospective partner FIs runs through BRIM's communications module. Email is the primary channel: BSB creates branded templates, personalizes by FI type and geography, and sends through the platform with full tracking across open rates, click-through, reply rates, and downstream conversion. Beyond email, BRIM gives BSB event management for tracking invitations, attendance, and follow-up from industry conferences and BSB-hosted events. Referral tracking captures referrals from existing partners like AFFINITY CREDIT UNION and tracks each referral source through to signed agreement. Co-marketing support covers joint materials with BSB branding and BRIM capabilities data — case studies, ROI models, and sandbox demo invitations. All channels feed into a single pipeline view in the admin portal so BSB sees every touchpoint with each prospect in one place.`,

  19: `BRIM's due diligence package is pre-built and battle-tested. Every current BRIM client — MANULIFE, CWB BANK, LAURENTIAN BANK, AFFINITY CREDIT UNION, UNI FINANCIAL, and ZOLVE — went through this process. For each prospect FI evaluation, BSB receives a completed compliance due diligence package and financial crime compliance certification ready to share with its own TPRM team, a PCI DSS AOC at the Service Provider level, a SOC 2 Type 2 report audited by Coalfire, an ISO 27001:2022 certificate, BCP/DR test results and recovery time documentation, and security and privacy policies. BRIM has no public regulatory enforcement actions since its founding. BSB customizes the due diligence workflow — adding fields, requiring additional documents, and setting scoring thresholds for auto-approval versus manual review. The onboarding module tracks each prospect's due diligence status with timestamps, document versions, and approval chains.`,

  20: `BRIM gives BSB a regulatory due diligence framework that BSB controls entirely. For each prospect FI, the platform validates charter status and regulatory standing (state/federal, active/inactive), BSA/AML program maturity including CIP, SAR/CTR filing history, and OFAC screening procedures, network compliance covering Visa and Mastercard membership and BIN eligibility, CRA rating for banks, and information security posture across encryption, access controls, and incident response. BSB customizes every element — which checks are mandatory versus optional, what scores trigger manual review, and which documents are required by FI type. A community bank's due diligence checklist differs from a credit union's or a fintech's. For federal credit unions specifically, BRIM gives BSB NCUA-specific requirement coverage. AFFINITY CREDIT UNION's onboarding included credit union-specific regulatory validation, which BRIM has productized for reuse across BSB's agent banking program.`,

  21: `BSB gets contracting support at every stage of partner onboarding. The template library covers master agreements, processing addenda, compliance exhibits, SLA schedules, data processing agreements, and technical integration specifications — these are production templates, the same ones used for MANULIFE, UNI FINANCIAL, and AFFINITY CREDIT UNION signings. BSB's legal team owns the templates and can modify terms by FI type, add BSB-specific clauses, adjust SLA thresholds, and create custom addenda. BRIM's templates are starting points, not constraints. The contracting workflow includes version tracking, redline management, approval routing, electronic signature integration, and executed document storage. BSB and the prospect FI collaborate within the portal — no email chains with competing document versions. Templates pre-incorporate Reg Z, TILA, CARD Act, and network rule requirements so BSB's legal review focuses on commercial terms, not regulatory baseline.`,

  23: `BRIM gives BSB support for both conversion scenarios it will encounter — FIs moving from self-issuance and FIs moving from another agent bank or processor. From self-issuance, BRIM works with the departing processor to extract account data, maps existing products to BSB's agent banking program structure, migrates balances and transaction history, and coordinates cardholder communication. The FI's cardholders experience a card reissue with updated branding and potentially improved features — not a disruption. From another agent bank or processor, BRIM handles the same data extraction and migration, plus BIN migration or new BIN issuance, token updates for card-on-file via Visa VAU and Mastercard ABU, and coordination with the departing agent bank for trailing activity. The track record is live: MANULIFE BANK migrated from Fiserv with 55,000 advisors and launched in four months. UNI FINANCIAL migrated from Collabria. ZOLVE completed a full BIN migration from i2c with CONTINENTAL BANK as US sponsor in 30 days. MONEY MART/MOMENTUM FINANCIAL migrated from Neo. LAURENTIAN BANK migrated from Fiserv (First Data). BSB can offer these as reference calls to prospective partner FIs.`,

  25: `BRIM gives BSB full ICA and BIN management across all three scenarios BSB will encounter. For BIN migration — moving an existing BIN to BRIM's platform — BRIM coordinates directly with Visa and Mastercard for BIN reassignment. Account data migrates with BIN continuity where possible. ZOLVE completed this in 30 days with CONTINENTAL BANK as US sponsor. For new BIN issuance, BRIM manages the application process with the network, configures the new BIN on the platform, and coordinates card reissuance. BSB's ICA structure determines BIN assignment, and BRIM gives BSB dedicated BINs per partner FI or shared BINs across the agent banking program. For ICA management, BRIM supports both BSB-owned ICAs with partner FI-specific BINs underneath and scenarios where partner FIs bring their own ICAs. For token and card-on-file continuity during BIN changes, Visa VAU pushes updated card credentials to merchants with recurring billing relationships — LAURENTIAN BANK's migration used VAU for this exact purpose. Mastercard ABU handles the same function for Mastercard-branded cards. MDES and VTS tokens update automatically when the underlying PAN changes during BIN migration, so cardholders' Apple Pay, Google Pay, and merchant-stored tokens continue working without any cardholder action. BRIM has executed this five times in production.`,

  27: `BRIM retains all data for a minimum of seven years — transactions, statements, correspondence, disputes, and collections activity — in BRIM's data center infrastructure with AES-256 encryption, certified under PCI DSS, SOC 2 Type 2, and ISO 27001. Access during and after conversion or deconversion is maintained without degradation. BSB has full access through the admin portal with cross-portfolio search, reporting, and export — converted and deconverted portfolios remain accessible. Partner FIs see only their own data through their dedicated portal, with historical data from pre-conversion available alongside post-conversion data in a single view with no toggling between systems. Cardholders access transaction history, statements, and rewards history through the mobile app and online banking — no separate portal for pre-conversion history. For deconversions, BSB retains read-only access to the departed FI's historical data per regulatory retention requirements. Data exports are available in standard formats for the receiving processor.`,

  29: `BRIM's rewards engine handles conversion across all three scenarios a converting portfolio will encounter. For same-type conversions (points-to-points or cashback-to-cashback), balances transfer at face value and the cardholder sees the same balance post-conversion with no action required. For currency conversions — for example, proprietary points to cashback — BRIM configures the conversion ratio, the platform executes the conversion at the account level, and generates a cardholder notice showing the old balance, conversion ratio, and new balance. For new rewards programs, BRIM's engine supports welcome bonuses, accelerated earn periods, and grandfathered tier status to ease the transition. Cardholder communications are staged: a notice 45 to 60 days pre-conversion explaining what changes, what stays the same, and any action required; a confirmation on conversion day with the new rewards balance, program summary, and earn guide; and an engagement check 30 days post-conversion covering rewards earned since conversion, available redemption options, and tier progress. BRIM's rewards engine runs programs for MANULIFE and Air France-KLM Flying Blue. It is not a bolt-on — it is built into the platform.`,

  34: `BRIM manages all requests through a centralized service portal. BSB and partner FIs submit requests for product changes, policy updates, configuration changes, bug reports, and feature requests. Each request auto-categorizes based on type and routes to the appropriate team. Priority and SLAs are tiered: P1 (system outage or security incident) receives a 15-minute response and a 4-hour resolution with 24/7 coverage. P2 (degraded service or high-impact bug) receives a 1-hour response and a 1-day resolution. P3 (standard changes or enhancements) receives a 4-hour response and a 5-day resolution. P4 (low-priority or cosmetic requests) receives a 1-day response and a 10-day resolution. BSB has admin-level visibility across all partner FI requests — real-time status, assignee, priority, timeline, and resolution notes. Partner FIs see only their own requests. Product changes and platform updates follow a defined release cadence — monthly feature releases with two weeks' advance notice, hotfixes as needed for P1 and P2 issues. BSB reviews and approves changes that affect the agent banking program before deployment to partner FIs.`,

  36: `BRIM pre-assembles BSB's TPRM compliance package and maintains ongoing monitoring dashboards. The documentation package is available on demand and includes a PCI DSS AOC at Service Provider level, SOC 2 Type 2 report audited by Coalfire covering security, availability, and confidentiality, an ISO 27001:2022 certificate, a completed compliance due diligence package and financial crime compliance certification, BCP/DR plan with test results and recovery time actuals, security and privacy policies, and no regulatory findings in five years of operation. Ongoing monitoring feeds cover SLA performance (authorization uptime, call center response times, and dispute resolution timelines by partner FI and aggregate), an incident log with every P1 and P2 incident including root cause, resolution time, and corrective action, regulatory reporting covering SAR filing status, complaint volumes, and network compliance metrics, and API feeds so BSB pulls compliance data directly into its own GRC platform. When partner FIs conduct their own TPRM reviews of BSB's agent banking program, BRIM provides BSB with a partner-ready evidence pack that BSB shares directly — no manual compilation required.`,

  37: `BRIM's control framework is built on PCI DSS at Service Provider level covering all cardholder data handling, encryption, access controls, and network security; SOC 2 Type 2 audited by Coalfire covering security, availability, and confidentiality trust service criteria; ISO 27001:2022 for information security management; Visa and Mastercard operating regulation compliance across dispute management, settlement, and reporting; and a BSA/AML program covering CIP, CDD, EDD, SAR/CTR filing, OFAC screening, and beneficial ownership. How this translates to BSB's oversight: BRIM delivers annual evidence packs — AOC, SOC 2 report, ISO certificate, penetration test summary with findings and remediation, and BCP/DR test results with recovery time actuals — in advance without BSB needing to request them. For each partner FI, a control obligation matrix maps which controls BRIM owns, which BSB owns, and which are shared. This simplifies partner FI audits and regulatory exams — responsibilities are defined upfront. BRIM has no public regulatory enforcement actions since its founding and can demonstrate its control framework directly to BSB's regulators on request.`,

  40: `BRIM gives BSB federal credit union regulatory compliance support built on its experience with AFFINITY CREDIT UNION. For NCUA-specific requirements, BRIM provides CAMEL metrics tracking at the credit union level covering capital adequacy, asset quality, management, earnings, and liquidity. Field-of-membership validation is includable as a due diligence step in the onboarding workflow. NCUA examination readiness is supported through data extracts formatted for NCUA examiners, including loan-level detail (credit cards are loans for NCUA purposes), delinquency and charge-off reporting, and concentration analysis. Federal Credit Union Act compliance covers interest rate caps, lending limits, and investment restrictions as they apply to credit card programs. BSB's due diligence framework is configurable through the BRIM admin portal — adding NCUA-specific document requirements, adjusting scoring models for credit union-specific risk factors, and creating a separate onboarding track for federal credit union partner FIs. AFFINITY CREDIT UNION operates a comparable agent banking model on BRIM's platform. The regulatory environment differs from NCUA, but the platform's ability to support credit union-specific compliance requirements is proven in production.`,

  41: `BRIM's onboarding training for partner FIs follows a structured three-phase curriculum. Phase 1 is a two-week orientation covering platform overview, program configuration walkthrough, key contacts, and escalation procedures for all partner FI staff involved in the credit card program. Phase 2 is two weeks of hands-on training with sandbox access for every trainee — they process test applications, manage test accounts, run reports, configure campaigns, and handle simulated disputes across role-based tracks for operations, compliance, marketing, and executives. Phase 3 is four weeks of go-live support with BRIM's team embedded during the first month of live operations for real-time questions, configuration adjustments, and process refinement. Materials include admin portal walkthroughs in both live and recorded formats, video tutorials, quick-reference guides, API documentation for technical teams, and sandbox environments that remain available post-training for ongoing practice. This curriculum is the same one used to onboard AFFINITY CREDIT UNION, MANULIFE (55,000 financial advisors), and UNI FINANCIAL.`,

  42: `BSB gets online training modules through a Learning Management System with separate tracks for branch and non-branch employees. Branch employee modules cover product overview (card types, rates, fees, and rewards — everything branch staff need to answer cardholder questions), application capture including how to submit applications through the platform and manage the instant decisioning workflow, cardholder FAQs on payments, statements, disputes, and rewards redemption, and compliance essentials covering Reg Z disclosures, TILA requirements, and privacy obligations. Non-branch employee modules cover platform administration, reporting and dashboards, campaign management, dispute processing, and compliance monitoring including regulatory reporting, threshold alerts, and audit preparation. All modules include completion tracking, quizzes, and certification. BSB can see which partner FI employees have completed training and which are outstanding — a single view across all partner FIs in the agent banking program.`,

  43: `Transition training is delivered by role with defined hour ranges per function. Executive orientation runs four to eight hours covering program economics, strategic dashboard, QBR structure, and escalation protocols. Operations training runs 20 to 40 hours across account lifecycle management, payment processing, statement generation, dispute handling, and collections workflows. Compliance training runs eight to 16 hours covering regulatory reporting, SAR filing, complaint management, disclosure review, and examination preparation. Technical training runs 16 to 24 hours across API integration, data feeds, GL mapping, settlement file processing, and system administration. CSR training runs eight to 12 hours covering cardholder inquiry handling, common scenarios, escalation procedures, and knowledge base navigation. Total per partner FI is 60 to 100 hours depending on program complexity. Post-transition, ongoing training runs quarterly for release updates covering new features and changed workflows, annually for compliance refreshers and network rule changes, on-demand through continuously updated LMS modules, and ad-hoc through webinars for significant platform changes or regulatory developments. BRIM assigns dedicated training staff during transition — not shared across simultaneous implementations.`,

  44: `Role-based training is standard across both BSB and partner FI staff. BSB roles include an executive track (program oversight, strategic dashboards, financial performance, QBR participation), operations manager track (cross-portfolio operations, SLA monitoring, escalation management, partner FI performance), compliance officer track (regulatory reporting, compliance monitoring, audit preparation, TPRM oversight), marketing and product manager track (product configuration, campaign management, partner FI brand management, offer design), and technical staff track (API management, data feeds, GL integration, system administration, release management). Partner FI roles include program manager (day-to-day program oversight, reporting, BSB coordination), operations (account management, disputes, collections, payment processing), compliance contact (regulatory reporting, complaint management, disclosure review), branch staff (application capture, cardholder inquiries, product knowledge), and marketing contact (campaign creation, cardholder communications, rewards program management). Each track has defined learning objectives, time estimates, and certification requirements. BSB customizes tracks by adding modules, adjusting content, and setting different certification thresholds for different partner FI types.`
};

let updated = 0;
Object.entries(patches).forEach(([idx, prose]) => {
  const i = parseInt(idx);
  if (data.questions[i]) {
    data.questions[i].paragraph = prose;
    updated++;
    console.log(`✓ idx ${i} [Partner Relationships] ${data.questions[i].requirement?.substring(0,60)}...`);
  }
});

fs.writeFileSync(DATA_PATH, JSON.stringify(data, null, 2));
console.log(`\nDone. ${updated} Partner Relationships paragraphs converted to prose.`);
