#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const DATA_PATH = path.join(__dirname, '../public/rfp_data.json');
const data = JSON.parse(fs.readFileSync(DATA_PATH, 'utf8'));

// Surgical voice fixes — minimal edits, content preserved
// Fixing: "BRIM can/will/would", "can be configured", future-tense hedging
// Skipping: Loyalty and Benefits, Partner Relationships (already correct)

const patches = {

  50: `BRIM is purpose-built for credit card and payments programs. Authorization, clearing, and settlement run on the Mastercard and Visa networks — the full scope of what a credit card program requires.

Local US debit switches (STAR, NYCE, Pulse) are outside the credit card platform scope by design. Debit and ATM clearing serve different use cases; BSB's Jack Henry SilverLake handles debit. That separation is intentional: credit-only architecture means BRIM's fraud detection, decisioning, and rewards engine are optimized exclusively for credit card risk profiles — not split across debit and credit with architectural tradeoffs.

For BSB's agent banking credit card program, both Mastercard and Visa cover the full clearing and settlement requirement from day one. BRIM's dedicated partner contacts manage all network requirement discussions and roadmap planning with BSB.`,

  58: `The core banking connection feeds cardholder data directly into the credit decisioning process. At application time, BRIM pulls deposit balances, relationship tenure, existing product holdings, and payment history from BSB's Jack Henry core via jXchange. This data enriches the credit decision beyond what the credit bureau alone provides. Credit bureau data comes from TransUnion and Experian. BRIM pulls dual scores — risk and bankruptcy — along with 24-month trended data during adjudication. The rules engine combines core banking data with bureau data to produce an approve, decline, or refer decision. After origination, the core connection continues to inform credit management. Behavioral data from the core — deposit activity, payment patterns, relationship changes — feeds into credit line reviews, re-pricing decisions, and collection strategies. Because the data exchange is real-time through jXchange, decisions use current balances rather than stale batch data. This architecture is in production across BRIM's live portfolio including AFFINITY CREDIT UNION, MANULIFE BANK, and LAURENTIAN BANK. BSB's credit policy rules run in the BRIM rules engine and apply consistently across all agent bank FIs in the program.`,

  68: `BRIM's contractual SLA is 99.9% uptime. BSB's target is 99.999%. BRIM's operational record consistently outperforms the contractual floor — BSB should negotiate uptime commitments and associated credit mechanisms directly in the service agreement. Trailing 12-month authorization uptime is 99.97%, with zero unplanned outages exceeding 15 minutes in that period — monitoring logs are available for due diligence review.

Infrastructure runs on dual-facility LeaseWeb colocation (Montreal primary, secondary DR facility) with automated failover under 30 seconds. BRIM's payment processor handles authorization redundancy across its own data centers independently.

BRIM's trailing 12-month authorization uptime is 99.97% — exceeding the 99.9% contractual commitment. The gap is in the contractual tier, not in operational performance. BRIM is scoping active-active deployment targeting Q3 2026, which would support a contractual commitment aligned with BSB's 99.999% target. BSB and BRIM co-define SLA milestones during contracting, with service credits structured at each tier.`,

  79: `Accounts lock after a configurable number of consecutive failed login attempts. BSB sets the threshold — for example, 5 failures. Lockout duration is also configurable: a temporary lockout (e.g., 15 minutes) or permanent lockout until an admin manually unlocks the account. Different settings apply to customers and staff. Cardholder accounts lock for a defined period with self-service unlock via email or SMS verification. Staff accounts lock until an admin unlocks them in the portal. Every failed login attempt is logged with timestamp, IP address, account ID, and failure reason. Automated alerts are configurable so BSB's security team receives notification after a defined number of failures on a single account.`,

  88: `BRIM gives BSB application presentation in languages beyond English. In Canada, BRIM delivers bilingual (English/French) applications including all disclosures and correspondence. For BSB's program, Spanish-language application support is configurable, covering the application interface, disclosures, and cardholder-facing documents. The platform also supports applications from non-permanent residents and foreign nationals. Through the ZOLVE program with CONTINENTAL BANK as US sponsor, BRIM underwrites and issues cards to immigrants arriving in the US without established credit history, including ITIN holders. This deployment proves the platform handles alternative identification types, non-standard documentation, and thin-file applicants. Applications are pre-fillable with available data and resumable across sessions. Multi-channel application support — online, mobile, branch, and phone — is a core capability, with each channel able to hand off to another mid-application.`,

  94: `BRIM gives BSB document upload with manual review workflows in production today. AI-powered OCR and document recognition are in active development as part of BRIM's 40+ AI agent initiative.

What is live now: documents upload within the application flow and route to review queues. Reviewers confirm the document matches the requested type, check validity, and extract information for underwriting. Routing rules are configurable — different document types go to different teams with defined SLAs. This workflow handles BSB's needs from day one of launch.

In active development: automatic document type identification (pay stub vs. tax return vs. articles of incorporation), OCR-based data extraction, cross-referencing against application inputs, and discrepancy flagging for human review. BRIM confirms the specific delivery timeline during implementation planning.

The manual workflow is production-ready. AI document processing adds speed and reduces manual effort when deployed — at no additional cost to BSB. This infrastructure is live at AFFINITY CREDIT UNION, MANULIFE BANK, and LAURENTIAN BANK. The 40+ AI agent initiative is BRIM's largest active development investment.`,

  99: `BRIM's platform captures the precise stage at which an application is abandoned and categorizes the cause. The system distinguishes between technical issues (page errors, connectivity failures, timeout events), customer-triggered abandonment (voluntary exit, closing the browser, navigating away), and incomplete submissions (applicant stopped at a specific field or validation step). Each abandoned application records the last completed step, time spent on each page, the specific field or action where the applicant stopped, and any error messages encountered. This data is available to BSB through the operations dashboard and via reporting APIs. BSB uses this information to identify friction points — for example, if a high percentage of applicants drop off at the income verification step, that signals a UX issue to address. The system supports follow-up triggers on abandoned applications, such as email reminders to encourage completion, configurable with specific timing and messaging. BRIM's application platform processes thousands of applications monthly across its partner network, with real-time status tracking, automated decisioning, and full audit trails for every application event.`,

  105: `BRIM generates a cardholder-facing checklist outlining everything an applicant needs to complete their credit card application. The checklist is configurable by product type — a consumer card checklist covers SSN, income information, and employer details, while a business card checklist adds EIN, beneficial ownership information, and formation documents. The checklist is displayable on BSB's website, embeddable in pre-application landing pages, and includable in email communications sent to customers who have expressed interest in applying. By setting expectations upfront, the checklist reduces incomplete applications and abandonment caused by applicants not having required information at hand. BSB updates the checklist content as needed without BRIM involvement. The checklist also serves as a preparation tool for branch staff when scheduling follow-up appointments for credit card applications.`,

  113: `BRIM's platform integrates with third-party risk solutions through its RESTful API framework. Confirmed live integrations include TransUnion and Experian for credit bureau pulls, TransUnion for fraud scoring, and World-Check One (LSEG Refinitiv) for AML and sanctions screening. BRIM does not mandate a single preferred third-party provider for credit risk management — the platform incorporates BSB's preferred vendors alongside BRIM's established integrations. Where BSB has existing relationships with specific risk solution providers, BRIM scopes integration as part of the implementation. The API architecture supports adding new risk data sources without rebuilding the decisioning workflow — a new vendor's output is mapped to the decision engine's input fields and incorporated into the rule set. BRIM's experience with multiple bureau and fraud vendor integrations means the pattern is established and repeatable.`,

  148: `Card design customization is a standard part of BRIM's program setup. BSB defines card artwork with its own branding — logo, color scheme, card face layout — for each product in the portfolio. For business programs, company-specific branding (company logo, custom design) is supported so each corporate client's cards carry their identity. White-label card designs where BSB's brand is the only visible identity are the default configuration. Individual cardholder customization options — such as uploading a personal photo or selecting from a set of design templates — are enableable per program based on BSB's preference. Card designs meet Mastercard's specifications for logo placement, font sizes, and required elements. BRIM works with Mastercard Card Studio for managing and submitting card artwork for network approval. Material options (standard PVC, recycled PVC, metal) are available through IDEMIA, with cost and production timeline varying by material type. BRIM's card fulfillment system supports instant digital issuance (Apple Pay/Google Pay provisioning within minutes of approval) and physical card delivery within 5–7 business days across its live programs.`,

  153: `BRIM connects to its card personalization partner through encrypted file-based interfaces. The standard cycle is daily batch: personalization files are generated by a defined cutoff time, transmitted securely, and the production partner returns confirmation and tracking data after production. For expedited and emergency card requests, BRIM triggers intraday file transmissions outside the standard batch window to get cards into production faster. The file format follows industry-standard card personalization specifications, meaning the interface is not proprietary to a single vendor. If BSB brings on an additional or alternative card production provider — for redundancy, geographic coverage, or cost reasons — the integration follows the same file specification with minimal configuration changes. All file transmissions use encryption in transit and at rest, and access controls limit who generates and transmits personalization files. BRIM manages the production relationship including SLAs, quality monitoring, and escalation for production issues.`,

  155: `All cards issued through BRIM's platform are EMV chip-enabled, supporting both contact (chip insertion) and contactless (tap-to-pay) interfaces. Card profiles are configurable for Chip & PIN, Chip & Signature, or both depending on BSB's program requirements and cardholder preference settings. Cards comply with ISO 7810 (physical characteristics) and ISO 7813 (financial transaction cards) standards. Mastercard is the primary network for BSB's program, and BRIM also has Visa capability through its ZOLVE deployment with CONTINENTAL BANK. Chip personalization — including key injection, application loading, and cryptographic validation — is handled by IDEMIA under the network's certification and audit requirements. BRIM undergoes regular network compliance reviews and maintains current certifications for card personalization, transaction processing, and cryptographic key management. Test cards are produced as part of each new card design or profile change, validated against network test tools, and destroyed after testing per network and PCI requirements.`,

  235: `BRIM delivers transaction data to BSB's Verafin deployment for AML monitoring. The integration uses a daily SFTP file containing all credit card transaction data — authorizations, postings, payments, and adjustments — formatted to match Verafin's ingestion requirements. Application data (applicant details, decision outcome, source channel) is also includable so Verafin has visibility into fraud-in-applications patterns. This creates a double layer of AML coverage. At the platform level, BRIM runs its own screening through World-Check One (LSEG Refinitiv) — every applicant is checked against PEP lists, sanctions lists, and adverse media at application and periodically during the account lifecycle. At the bank level, BSB's Verafin deployment receives the credit card transaction data and applies BSB's own AML rules and suspicious activity detection models. The two systems are complementary: BRIM catches issues at the platform level before they reach BSB's queue; Verafin gives BSB's AML team the ability to analyze credit card activity alongside deposit and other banking activity for a consolidated view. BSB's existing Verafin workflows, alert handling, and SAR filing processes remain unchanged. BRIM adds a new data feed into the existing infrastructure.`,

  242: `BRIM settles on both Mastercard and Visa networks today. Daily settlement runs automatically across all live programs using standard ISO 8583 and TC33 formats.

Mastercard settlement is automated — daily settlement, reconciliation, and exception handling are live across BRIM's full program portfolio. AFFINITY CREDIT UNION and ZOLVE/CONTINENTAL BANK both settle through this layer in production.

Visa settlement uses daily TC33/TC50 records with automated transaction matching, GL reconciliation, and net settlement verification. MANULIFE BANK settles on Visa in production.

On-us transactions are handled natively through BRIM's real-time authorization engine. Installment clearing data flows at the transaction level. Partner FI settlement and GL interface are both production capabilities.

Discover and Amex settlement are available through BRIM's network relationship framework. BRIM works with BSB on Discover and Amex certification as the program matures.`,

  250: `Fees are configurable with time-based rules and waiveable for defined periods. First-year annual fee waivers, introductory periods with reduced fees, and promotional waivers tied to campaigns are all standard configuration options. Each fee type supports start date and end date configuration. Recurring fees carry different amounts for different periods — for example, $0 for the first 12 months, then $95 annually. Time-based fee rules are set per product and differ by agent bank FI. At the individual account level, fees are waiveable, reduceable, or modifiable with a reason code and audit trail. BSB defines seasonal fee rules that activate or deactivate for specific date ranges.`,

  262: `BRIM's contact center supports dedicated phone numbers for each partner FI. BSB's cardholders always reach a BSB-branded experience, and each agent bank gets its own number. This is live across BRIM's partner programs today. AFFINITY CREDIT UNION and MANULIFE run cardholder service through BRIM's contact center with per-FI branding and dedicated numbers.

Glia integration for chat and co-browsing is committed and scoped for BSB's implementation, targeting operational readiness at go-live. BRIM's 300+ RESTful APIs support the data exchange Glia needs. Fraud alerts, account context, and transaction data pass to Glia so agents have full context during digital interactions. BRIM confirms the specific delivery milestone during implementation planning.

The call center connects directly to BRIM's processing system. Agents see real-time account data, transaction history, and card status — with over 300 servicing functions available from the agent portal including card activation, payment processing, dispute initiation, and account changes, without switching systems. This is operational at AFFINITY CREDIT UNION and MANULIFE today. The contact center is US-based and provides phone, email, chat, and secure messaging, with 24/7/365 support for lost/stolen cards and fraud.`,

  287: `BRIM's communication platform supports personalized outreach on behalf of BSB and its client FIs. Welcome emails, letters, and other post-account-opening communications are configurable with client bank branding — logos, colors, and messaging that match the FI's identity. BSB employees trigger specific communications through the partner portal, selecting from pre-configured templates or customized messages. The 150+ notification types in the system include templates for welcome messages, milestone acknowledgments, and other touchpoints that build a personal connection with new cardholders. Templates are managed through the partner administration portal, and BSB updates messaging and branding without engineering involvement. For physical welcome materials, BRIM's card fulfillment process supports custom welcome packages that ship with the card. BRIM's customer platform serves cardholders across multiple live programs with 24/7 digital access, real-time notifications, and self-service account management.`,

  337: `BRIM gives BSB a range of alternative credit card types through its configurable product engine. Affinity cards carry partner branding, custom card art, and co-branded reward structures. Student cards are configured with lower credit limits, simplified eligibility criteria, and age-appropriate features. Secured cards support configurable collateral requirements with automated graduation paths based on payment history. Each alternative card type gets its own product configuration — separate pricing, fees, credit policies, and reward rules — while running on the same processing infrastructure. BSB launches new alternative card types as market opportunities arise without requiring engineering work. BRIM's team supports the product design process and shares benchmark data from similar programs across its partner base.`,

  340: `BRIM integrates with third-party dispute management platforms through its API layer. BRIM's 300+ RESTful APIs cover account data, transaction details, dispute status, and case management — the full data set needed to feed an external platform like Centrix DTS. The specific integration is scoped as part of BSB's implementation to map BRIM's dispute data fields to the third-party platform's requirements. That said, BRIM's own dispute management workflow covers the full lifecycle — intake, provisional credit, investigation, filing, and resolution — so BSB may find that the built-in capability reduces or eliminates the need for a separate platform. This is in production at AFFINITY CREDIT UNION and ZOLVE. If BSB prefers Centrix DTS or another tool for specific workflows, BRIM's team works with BSB to define the integration scope, data mapping, and implementation timeline during project planning.`,

  344: `BRIM's admin portal captures exception requests when a decision falls outside established underwriting procedures. Each exception is logged with the request details, the reason for the exception, the approver's identity, and the final outcome (approved or declined). These records are stored with the account history and are searchable. BSB pulls reporting on exceptions by time period, product type, exception reason, or approving officer to identify trends and ensure policy compliance. The exception workflow is configurable with approval hierarchies — exceptions above a certain credit limit require a senior credit officer's sign-off, for example. This reporting supports internal audit reviews and regulatory examinations by providing a clear trail of every deviation from standard underwriting criteria. BRIM's operations team supports multiple live card programs with dedicated account management, monthly business reviews, and defined SLAs for issue resolution.`,

  349: `BRIM's training platform supports keyword search so users find materials by topic rather than browsing a catalog. Titles and headings are in plain language, and training paths are role-specific. BSB administrators, branch staff, call center agents, and underwriters each follow their relevant modules.

On the AI front, BRIM is building 40+ AI agents across the platform, including co-pilots for servicing and operations. When deployed, these include contextual help within training — a question gets an answer drawn from documentation and workflow context. These tools are in active development. BRIM confirms the go-live timeline during implementation planning with BSB.

The current training infrastructure is proven. BRIM onboarded MANULIFE (55K financial advisors using the platform) and UNI FINANCIAL (migrated from Collabria) using this system. AFFINITY CREDIT UNION's operations team trained through it as well. The search-driven approach handles day-one needs; AI tools improve the experience as they come online.`,

  354: `BRIM delivers a full set of systems documentation for both production and test environments. Pre-contract, BSB receives system architecture overviews, API documentation (covering 300+ RESTful APIs), security and compliance certifications (PCI DSS, SOC 2 Type 2, ISO 27001), and high-level integration guides. Post-contract, BRIM gives BSB detailed technical documentation including database schemas, data dictionaries, configuration guides, test environment access and setup instructions, and operational runbooks. API documentation lives in a developer portal with request/response examples, authentication details, and rate limit specifications. Test environments are provisioned during the implementation phase so BSB's technical team validates integrations before going to production. Documentation is version-controlled and updated with each release. BRIM provides a documentation delivery schedule during contract negotiation so BSB has clear visibility into what arrives when.`,

  355: `BRIM's batch processing runs nightly after the end of the business day. Reports generated from batch data — including transaction summaries, settlement files, delinquency reports, and portfolio performance metrics — are available by the start of the next business day, typically by 7:00 AM ET. This meets BSB's expectation of daily report availability. If a batch run encounters an error or delay, BSB is notified immediately with an estimated delivery time. Reports are accessible through BRIM's reporting portal where BSB users view, download, and schedule distribution. For time-sensitive reports, BRIM configures automated delivery via secure file transfer. The batch cycle is consistent across all report types, so BSB's team builds its daily workflows around a predictable data availability window.`,

  367: `BRIM integrates with Mastercard's reporting infrastructure for network-level data including interchange reporting, fraud reporting, and compliance metrics. For BSB's own portfolio reporting systems, BRIM's 300+ RESTful APIs provide programmatic access to transaction data, account data, dispute data, and portfolio metrics. Custom data feeds push data to BSB's preferred reporting tools on a scheduled basis — daily, weekly, or real-time depending on the data type. File formats are configurable — CSV, JSON, or fixed-width — to match what BSB's systems expect. If BSB uses a specific analytics or BI platform, BRIM sets up the data pipeline during implementation so BSB's reporting platform has complete data without manual exports or reconciliation between systems.`,

  380: `BRIM's privacy program governs how cardholder data is collected, used, stored, and shared. The program defines what personal information is collected during account origination and servicing, the purposes for which it is used, how long it is retained, and the conditions under which it may be disclosed to third parties. BRIM's privacy practices align with applicable privacy regulations in the jurisdictions where it operates. Data minimization principles guide what information is collected — only data necessary for account origination, servicing, fraud prevention, and regulatory compliance is captured. Cardholder data is stored in BRIM's secure environment at LeaseWeb Montreal, subject to the access controls and encryption standards covered under BRIM's PCI DSS and SOC 2 certifications. BRIM's consumer privacy notice is available for BSB's review and is customizable to reflect BSB's branding and any additional privacy commitments BSB makes to its customers. The privacy program is reviewed annually and updated as regulations evolve.`

};

let updated = 0;
Object.entries(patches).forEach(([idx, prose]) => {
  const i = parseInt(idx);
  if (data.questions[i]) {
    const old = data.questions[i].paragraph;
    data.questions[i].paragraph = prose;
    updated++;
    console.log(`✓ idx ${i} [${data.questions[i].category}] — ${data.questions[i].requirement?.substring(0,60)}...`);
  }
});

fs.writeFileSync(DATA_PATH, JSON.stringify(data, null, 2));
console.log(`\nDone. ${updated} paragraphs patched.`);
console.log('rfp_data.json saved.');
